services:
  app:
    container_name: go-app-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    environment:
      MYSQL_PORT_INTERNAL: ${MYSQL_PORT_INTERNAL:-3306}
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app
          ignore:
            - .git/
            - vendor/
            - tmp/
            - '*.md'
            - .env
            - compose.yml
            - Dockerfile

  db:
    image: mysql:8.0
    container_name: mysql-db-dev
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
